name: Sync and merge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Upstream Sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main
          upstream_sync_repo: https://github.com/Dug-F/atedo
          upstream_sync_branch: main

  
          
    # Toggle to spawn `sync-upstream-repo` with time logs
               
          

