name: Sync and merge
on:
    workflow_dispatch:
    schedule:
    - cron: '0 0 * * *'

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2
          - name: sync and merge upstream
            uses: dabreadman/sync-upstream-repo@v1.0.0.b
            with:
    # URL of gitHub public upstream repo
                upstream_repo: https://github.com/Dug-F/atedo
    # Branch to merge from upstream (defaults to downstream branch)
                upstream_branch: main
    # Branch to merge into downstream
                downstream_branch: main
    # GitHub Bot token
                
    # Git fetch arguments
                
    # Git merge arguments 
    # Git push arguments
                
    # Toggle to spawn `sync-upstream-repo` with time logs
               
          

